[[pages]]
path = "streamlit_app.py"
name = "Home"
icon = "ğŸ”¥"

[[pages]]
path = "pages/Chatbot.py"
name = "Chatbot"
icon = "ğŸ¤–"

[[pages]]
path = "pages/Tableau.py"
name = "Tableau"
icon = "ğŸ–¥ï¸"

[[pages]]
path = "pages/Docusign.py"
name = "Docusign"
icon = "ğŸ“‘"